######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 19 18:52:29 2008
######################################################################

TEMPLATE = app
TARGET = openglscene
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += openglscene.h point3d.h model.h
SOURCES += main.cpp model.cpp openglscene.cpp

QT += opengl concurrent

win32:LIBS += -lOpengl32 \
              -lglu32
